### PR TITLE
functional improvement

### PR DESCRIPTION
**Pull request by Droid-MAX**
support for custom port numbers and fixed some issues.

### CODE REVIEW

**Comment by Ekultek** [comment]
Looks fine to me, I’m kind of fond of the impacket.impacket though. Do you have any objections in keeping that?

**Comment by Droid-MAX** [comment]
Why not use the way to install impacket online? Is the original impacket library modified?

**Comment by Ekultek** [comment]
I think it’s funny when people get confused. And idk, I just like it. So fix that and I’ll merge

**Comment by Droid-MAX** [comment]
You can use this commad:
` pip install git+https://github.com/SecureAuthCorp/impacket.git@master `

**Comment by Droid-MAX** [comment]
Just stop here, I feel that BlueKeep has been modified to meet my needs, and I will archive this repo in my github.

**Comment by Ekultek** [comment]
Thought I already merged this sorry

**Pull request merged**
